#  5 Dec 2020 14:40
#+TITLE: DLB aka: Dirty Little Book ("Sudelbüchlein")

* à propos Sudelbüchlein
  :PROPERTIES:
  :DATE:     <2020-12-07 Mon 08:27>
  :END:

https://en.wikipedia.org/wiki/Orgelb%C3%BCchlein#/media/File:Schlosskirche_Weimar_1660.jpg

https://fr.wikipedia.org/wiki/L%27%C5%92uvre_au_noir#/media/Fichier:Image-Amphitheatrum_sapientiae_aeternae_-_Alchemist's_Laboratory_with_text.jpg

* Sense Substitution (Virtual)
** ISEA 2011 Peter Weibel Keynote
** Sense Substitution in Sense-Monopolistic Arts
** Synaesthetic Arts

What do I mean by Synaesthetic Arts?  ... 

The characteristic synaesthetic function is more present in the Arts than commonly thought. But possibly different art forms behave differently in this respect.
*** Music
*** Pictorial Arts / Painting
*** Architecture
*** Poetry ...
*** Theatre / Stage Arts
*** Dance
** Συναισθησία και Θέατρο
   :PROPERTIES:
   :DATE:     <2020-12-07 Mon 08:26>
   :END:
*** Bando Tamasaburo on 

Kabuki Dance Bando Tamasaburo Yamanba SaveYouTube com]
https://www.youtube.com/watch?v=GrKiardpfnw

Compare with Maya Plissetskaya' Dying Swan Performance
https://www.youtube.com/watch?v=Luz5g-doa34
Maya Plisetskaya, age 61, dances Dying Swan

Message from Tamasaburo Bando V - THE 2011 KYOTO PRIZE
https://www.youtube.com/watch?v=gonFvhsh0Qc


** What's on with this "Gesamtkunswerk?" thing
   :PROPERTIES:
   :DATE:     <2020-12-07 Mon 08:23>
   :END:

A very loud and equally cheap word that promptly raised an aesthetic/ideological crusade.
* Embodied Cognition / Embodied Performance
  :PROPERTIES:
  :DATE:     <2020-12-07 Mon 08:52>
  :END:



* 3 Instruments in History
** Theorbe
** Carnyx
** Hindewhu
* Boulez on history and now

https://www.youtube.com/watch?v=pzQF3_Q8xGs

Boulez: Lucerne Festival Academy Documentary (English Subtitles)

History is not divided from now, but now is connected to history, often straddling centuries.
* Construction - Algorithm - Code - Writing - Encoding - Compression
  :PROPERTIES:
  :DATE:     <2020-12-06 Sun 09:49>
  :END:
** Constructible Numbers
** Writing as Encoding but also Compression - Distillation
** Notation / Theory (Σημειογραφία / Θεωρία)
   :PROPERTIES:
   :DATE:     <2020-12-07 Mon 08:23>
   :END:
*** Σημειογραφία: Καταγραφή ή Προδιαγραφή;
*** Προδιαγραφή: Αλγόριθμος κατασκευής;
* L'oeuvre au noir. Alchemy and Mephistopheles
  :PROPERTIES:
  :DATE:     <2020-12-06 Sun 09:50>
  :END:
** Marguerite Yourcenar: L'Œuvre au noir
   :PROPERTIES:
   :DATE:     <2020-12-07 Mon 08:23>
   :END:
 Heinrich Khunrath (1595): Amphitheatrum sapientiae aeternae.
 Le Laboratoire de l'alchimiste.

 L'Œuvre au noir wikipedia french.
** Cohen brothers: Fargo, Season 3
   :PROPERTIES:
   :DATE:     <2020-12-07 Mon 08:23>
   :END:
* Polynomials, Cryptocurrency, Encryption, sharing secrets

How to keep an open secret with mathematics. https://www.youtube.com/watch?v=K54ildEW9-Q&t=7s

Compare to polynomials, curves, linear algebra

